### ISSUE TITLE
Deploying on Cloudflare Pages, script_too_large?

### ISSUE THREAD

**Issue by matthewjewell** [nuxt-modules/og-image#193]
Hi,

I think this may be misconfiguration or misunderstanding on my part rather than an issue, but just to check:

Tried deploying a branch with a simple template, it works well locally, but with the 1mb worker limit on Pages (free) I get the `workers.api.error.script_too_large` error as the compiled-wasm file is 2.4mb. 

Is there a way around this or is the package not usable with the 1mb limit?

Thanks!

**Comment by ExEr7um** [comment]
Same issue. OG Image adds `1.8MB` compressed.

**Comment by ijkml** [comment]
Hi, Harlan :wave:.
Ran into this issue, too.

**Comment by harlan-zw** [comment]
If you want to generate runtime images with Satori on Cloudflare there isn't a way around this (for now). This is due to upstream dependency WASM sizes that I have no control over.

If you're happy to prerender all of your images then you can follow my [comment](https://github.com/nuxt-modules/og-image/issues/210#issuecomment-2109194076).

**Comment by matthewjewell** [comment]
Thanks really useful, thanks for the reply @harlan-zw

**Comment by harlan-zw** [comment]
Please use the new Zero Runtime mode if you can prerender all of the images you need https://nuxtseo.com/og-image/guides/zero-runtime
